sm8350-common: Drop los/dfm & Declare missing HALs in DFM
Log:
The following HALs in device manifest are not declared in FCM <= level 5:
  android.hardware.bluetooth.audio.IBluetoothAudioProviderFactory/default (@4)
  android.hardware.boot@1.2::IBootControl/default
  android.hardware.drm.IDrmFactory/clearkey (@1)
  android.hardware.health.IHealth/default (@3)
  android.hardware.memtrack.IMemtrack/default (@1)
  android.hardware.power.IPower/default (@4)
  android.hardware.thermal.IThermal/default (@1)
  android.hardware.usb.IUsb/default (@1)
  android.hardware.wifi.IWifi/default (@2)
  android.hardware.wifi.hostapd.IHostapd/default (@2)
  android.hardware.wifi.supplicant.ISupplicant/default (@3)
  vendor.lineage.health.IChargingControl/default (@1)
  vendor.lineage.livedisplay@2.0::IPictureAdjustment/default
  vendor.lineage.livedisplay@2.1::ISunlightEnhancement/default
  vendor.lineage.powershare@1.0::IPowerShare/default
  vendor.lineage.touch@1.0::IHighTouchPollingRate/default
  vendor.lineage.touch@1.0::ITouchscreenGesture/default
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    vendor.lineage.health.IChargingControl/default (@1)
    vendor.lineage.livedisplay@2.0::IPictureAdjustment/default
    vendor.lineage.livedisplay@2.1::ISunlightEnhancement/default
    vendor.lineage.powershare@1.0::IPowerShare/default
    vendor.lineage.touch@1.0::IHighTouchPollingRate/default
    vendor.lineage.touch@1.0::ITouchscreenGesture/default
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility matrices with FCM version >= 5.
3. For new platform HALs, add them to any framework compatibility matrix with FCM version >= 5 where applicable.
4. For device-specific HALs, add to DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.: Success
INCOMPATIBLE

ref: https://gist.github.com/SebaUbuntu/ec053a00a9988eaea091fb1cc1f19324
https://github.com/KanishkTheDerp/device_google_crosshatch/commit/5a630b2d48787e13904786dfc8cb0614cb606203
Signed-off-by: TogoFire <togofire@mailfence.com>
Change-Id: I9aa6063857f4a977a820c7b3fd36d16350aef062